// Catalogue of real astrophysical phenomena — pulsars, magnetars, black holes,
// quasars/AGN, supernova remnants, nebulae, star-forming regions, exotic stars,
// exoplanet systems and gravitational-wave events. Each entry carries a short
// documentation blurb and key facts and is positioned by RA/Dec (degrees) and a
// distance string. All data is from public catalogues (no licensed assets).
// ra: right ascension in DEGREES (0–360). dec: declination in degrees (−90..90).

export const PHENOM_CATS = {
  pulsar:      { label: 'Pulsars',                color: '#7fe0c8' },
  magnetar:    { label: 'Magnetars',             color: '#ff8f6b' },
  blackhole:   { label: 'Black holes',           color: '#c88bff' },
  quasar:      { label: 'Quasars & AGN',         color: '#ffd27f' },
  snr:         { label: 'Supernova remnants',    color: '#ff9fb0' },
  nebula:      { label: 'Nebulae',               color: '#e08fd4' },
  starforming: { label: 'Star-forming regions',  color: '#9fd4ff' },
  star:        { label: 'Extreme stars',         color: '#ffe9a8' },
  exoplanet:   { label: 'Exoplanet systems',     color: '#9fffb0' },
  gw:          { label: 'Gravitational waves',   color: '#b0c0ff' },
};

// helper to keep entries terse: [id, name, cat, raDeg, dec, dist, doc, facts]
const P = (id, name, cat, ra, dec, dist, doc, facts) => ({ id, name, cat, ra, dec, dist, doc, facts });

export const PHENOMENA = [
  // ---- Pulsars (rotating neutron stars) ----
  P('PSR B0531+21', 'Crab Pulsar', 'pulsar', 83.633, 22.014, '6,500 ly',
    'The neutron-star heart of the Crab Nebula, born in the supernova seen in 1054 AD. It spins 30 times a second and powers the entire nebula.',
    [['Spin period', '33.5 ms'], ['Type', 'Young pulsar'], ['Remnant of', 'SN 1054']]),
  P('PSR B0833-45', 'Vela Pulsar', 'pulsar', 128.836, -45.176, '960 ly',
    'One of the brightest radio pulsars and a famous gamma-ray source, sitting inside the Vela supernova remnant.',
    [['Spin period', '89 ms'], ['Age', '~11,000 yr']]),
  P('PSR B1919+21', 'LGM-1', 'pulsar', 290.0, 21.88, '2,300 ly',
    'The very first pulsar ever detected, found by Jocelyn Bell Burnell in 1967. Its clockwork pulses were briefly nicknamed "Little Green Men".',
    [['Spin period', '1.337 s'], ['Discovered', '1967']]),
  P('PSR B1257+12', 'Lich', 'pulsar', 194.583, 12.68, '2,300 ly',
    'A millisecond pulsar orbited by the first exoplanets ever confirmed (1992): three small worlds circling a dead star.',
    [['Spin period', '6.2 ms'], ['Planets', '3'], ['First exoplanets', '1992']]),
  P('PSR B1937+21', 'First Millisecond Pulsar', 'pulsar', 294.911, 21.583, '11,700 ly',
    'The first millisecond pulsar discovered (1982); it spins 642 times per second, rivalling the precision of atomic clocks.',
    [['Spin period', '1.558 ms'], ['Spins/sec', '642']]),
  P('PSR B1913+16', 'Hulse–Taylor Binary', 'pulsar', 288.0, 16.11, '21,000 ly',
    'A pulsar in a binary with another neutron star. Its decaying orbit gave the first proof that gravitational waves exist, a 1993 Nobel Prize.',
    [['Spin period', '59 ms'], ['Proved', 'Gravitational waves']]),
  P('PSR J0737-3039', 'Double Pulsar', 'pulsar', 114.464, -30.66, '2,400 ly',
    'The only known system of two pulsars orbiting each other, a unique natural laboratory for testing general relativity.',
    [['Periods', '23 ms & 2.8 s'], ['Pulsars', '2']]),
  P('PSR J0437-4715', 'Nearest Millisecond Pulsar', 'pulsar', 69.316, -47.252, '510 ly',
    'The closest and brightest millisecond pulsar, a precision timing target with a white-dwarf companion.',
    [['Spin period', '5.76 ms'], ['Nearest of its kind', 'yes']]),
  P('Geminga', 'Geminga', 'pulsar', 98.476, 17.77, '815 ly',
    'A nearby gamma-ray pulsar that is nearly radio-silent, one of the brightest sources in the gamma-ray sky.',
    [['Spin period', '237 ms'], ['Type', 'Gamma-ray pulsar']]),

  // ---- Magnetars (ultra-magnetic neutron stars) ----
  P('SGR 1806-20', 'SGR 1806−20', 'magnetar', 272.16, -20.41, '~42,000 ly',
    'The most magnetic object known. In 2004 it released a giant flare that briefly outshone the full Moon in gamma rays and disturbed Earth\'s ionosphere from across the galaxy.',
    [['Field', '~2×10¹¹ T'], ['2004 flare', 'Brightest ever']]),
  P('SGR 1900+14', 'SGR 1900+14', 'magnetar', 286.8, 9.32, '~20,000 ly',
    'A magnetar whose 1998 giant flare forced satellites to safe-mode and revealed the soft-gamma-repeater class.',
    [['Spin period', '5.2 s'], ['Giant flare', '1998']]),
  P('1E 2259+586', '1E 2259+586', 'magnetar', 345.28, 58.88, '~10,000 ly',
    'An anomalous X-ray pulsar in the supernova remnant CTB 109, a textbook magnetar.',
    [['Spin period', '7 s'], ['In SNR', 'CTB 109']]),
  P('Swift J1818', 'Swift J1818.0−1607', 'magnetar', 274.51, -16.13, '~14,000 ly',
    'One of the fastest-spinning magnetars and a rare radio-loud one, a likely very young neutron star.',
    [['Spin period', '1.36 s'], ['Age', '~470 yr']]),
  P('XTE J1810-197', 'XTE J1810−197', 'magnetar', 272.46, -19.73, '~10,000 ly',
    'The first magnetar found to emit radio pulses, switching its radio emission on and off over years.',
    [['Spin period', '5.5 s'], ['Radio', 'Transient']]),

  // ---- Black holes (stellar-mass & X-ray binaries) ----
  P('Cygnus X-1', 'Cygnus X-1', 'blackhole', 299.59, 35.20, '7,200 ly',
    'The first object widely accepted as a black hole. It pulls gas from a blue supergiant companion, and was the subject of a famous Hawking–Thorne bet.',
    [['Mass', '~21 M☉'], ['Companion', 'Blue supergiant'], ['Confirmed', '1971']]),
  P('V404 Cygni', 'V404 Cygni', 'blackhole', 306.02, 33.87, '7,800 ly',
    'A black-hole binary that erupts every few decades; its 2015 outburst was one of the brightest X-ray events of the era.',
    [['Mass', '~9 M☉'], ['Outburst', '2015']]),
  P('GRS 1915+105', 'GRS 1915+105', 'blackhole', 288.80, 10.95, '36,000 ly',
    'A microquasar firing jets of plasma at apparently faster-than-light (superluminal) speeds, an illusion of relativistic motion.',
    [['Mass', '~12 M☉'], ['Jets', 'Superluminal']]),
  P('GRO J1655-40', 'GRO J1655−40', 'blackhole', 253.50, -39.85, '11,000 ly',
    'A microquasar whose spinning black hole drags spacetime around it (frame dragging), measured from its X-ray flicker.',
    [['Mass', '~6.3 M☉'], ['Spin', 'Rapid']]),
  P('A0620-00', 'A0620−00', 'blackhole', 95.68, -0.35, '3,500 ly',
    'The nearest known black hole to Earth, quietly orbiting an orange dwarf star.',
    [['Mass', '~6.6 M☉'], ['Nearest BH', '~3,500 ly']]),
  P('LMC X-1', 'LMC X-1', 'blackhole', 84.91, -69.74, '163,000 ly',
    'A black-hole binary in the Large Magellanic Cloud, devouring a hot massive companion.',
    [['Mass', '~10.9 M☉'], ['Galaxy', 'LMC']]),
  P('Sgr A*', 'Sagittarius A*', 'blackhole', 266.417, -29.008, '26,700 ly',
    'The supermassive black hole at the centre of the Milky Way, imaged by the Event Horizon Telescope in 2022. Four million times the Sun\'s mass.',
    [['Mass', '4.3 million M☉'], ['Imaged', '2022 (EHT)']]),

  // ---- Quasars & active galactic nuclei ----
  P('3C 273', '3C 273', 'quasar', 187.278, 2.052, '2.4 Gly',
    'The first quasar ever identified (1963) and the optically brightest in our sky: a supermassive black hole outshining its whole galaxy.',
    [['Type', 'Quasar'], ['First identified', '1963'], ['Luminosity', '~4×10¹² L☉']]),
  P('TON 618', 'TON 618', 'quasar', 184.36, 31.73, '10.4 Gly',
    'Home to one of the most massive black holes known, tens of billions of solar masses, blazing across the early universe.',
    [['BH mass', '~40 billion M☉'], ['Type', 'Hyperluminous quasar']]),
  P('OJ 287', 'OJ 287', 'quasar', 133.70, 20.11, '3.5 Gly',
    'A blazar containing a binary supermassive black hole; the smaller hole plunges through the larger one\'s disk every ~12 years, causing bright flares.',
    [['Type', 'Blazar (binary)'], ['Flare cycle', '~12 yr']]),
  P('Mrk 421', 'Markarian 421', 'quasar', 166.114, 38.21, '397 Mly',
    'One of the closest and best-studied blazars, with a jet pointed almost straight at Earth; a bright TeV gamma-ray source.',
    [['Type', 'Blazar'], ['Jet', 'Aimed at us']]),
  P('M77', 'NGC 1068 (Messier 77)', 'quasar', 40.67, -0.01, '47 Mly',
    'A nearby Seyfert galaxy with an obscured active nucleus, a recent source of high-energy cosmic neutrinos.',
    [['Type', 'Seyfert galaxy'], ['Neutrinos', 'Detected']]),

  // ---- Supernova remnants ----
  P('Cas A', 'Cassiopeia A', 'snr', 350.85, 58.815, '11,000 ly',
    'The expanding debris of a star that exploded ~340 years ago, the brightest radio source beyond the Sun and a JWST showpiece.',
    [['Age', '~340 yr'], ['Type', 'SNR']]),
  P('Tycho', "Tycho's Supernova Remnant", 'snr', 6.32, 64.14, '~10,000 ly',
    'Remnant of the bright supernova Tycho Brahe recorded in 1572, a Type Ia explosion that reshaped European astronomy.',
    [['Event', 'SN 1572'], ['Type', 'Ia']]),
  P('Kepler', "Kepler's Supernova Remnant", 'snr', 262.67, -21.49, '~20,000 ly',
    'Remnant of SN 1604, the most recent naked-eye supernova seen in the Milky Way, observed by Johannes Kepler.',
    [['Event', 'SN 1604'], ['Last galactic SN seen', 'yes']]),
  P('Veil', 'Veil Nebula (Cygnus Loop)', 'snr', 312.75, 30.72, '2,400 ly',
    'Delicate filaments of a supernova that detonated ~10,000–20,000 years ago, spanning six full Moons of sky.',
    [['Age', '~10–20 kyr'], ['Type', 'SNR']]),
  P('SN 1006', 'SN 1006 Remnant', 'snr', 225.59, -41.94, '7,200 ly',
    'Remnant of the brightest stellar event in recorded history (1006 AD), bright enough to read by at night.',
    [['Event', 'SN 1006'], ['Brightest SN recorded', 'yes']]),

  // ---- Nebulae (emission, planetary, dark) ----
  P('Helix', 'Helix Nebula', 'nebula', 337.41, -20.84, '655 ly',
    'One of the closest planetary nebulae: the glowing shroud a Sun-like star casts off as it dies, often called the "Eye of God".',
    [['Type', 'Planetary nebula'], ['Central star', 'White dwarf']]),
  P('Cat\'s Eye', "Cat's Eye Nebula", 'nebula', 269.64, 66.63, '3,300 ly',
    'An intricate planetary nebula of nested shells and jets, revealing the complex death throes of a dying star.',
    [['Type', 'Planetary nebula'], ['Structure', 'Nested shells']]),
  P('Horsehead', 'Horsehead Nebula', 'nebula', 85.24, -2.46, '1,375 ly',
    'A dark column of dust silhouetted against glowing hydrogen in Orion, one of the most recognisable shapes in the sky.',
    [['Type', 'Dark nebula'], ['In', 'Orion']]),
  P('NGC 7000', 'North America Nebula', 'nebula', 314.75, 44.52, '2,590 ly',
    'A vast emission nebula whose shape mirrors the continent of North America, lit by hot young stars.',
    [['Type', 'Emission nebula'], ['Size', '~100 ly']]),
  P('Rosette', 'Rosette Nebula', 'nebula', 97.95, 4.95, '5,200 ly',
    'A flower-shaped emission nebula with a young star cluster carving a cavity at its heart.',
    [['Type', 'Emission nebula'], ['Cluster', 'NGC 2244']]),

  // ---- Star-forming regions ----
  P('30 Doradus', 'Tarantula Nebula', 'starforming', 84.68, -69.10, '160,000 ly',
    'The most active starburst region in the Local Group, in the Large Magellanic Cloud, home to the most massive stars known.',
    [['Type', 'Starburst'], ['Hosts', 'R136 cluster']]),
  P('Rho Oph', 'Rho Ophiuchi Cloud', 'starforming', 246.79, -24.62, '460 ly',
    'The nearest stellar nursery, a colourful complex of dust and protostars, a JWST first-anniversary image.',
    [['Type', 'Molecular cloud'], ['Nearest nursery', 'yes']]),
  P('NGC 3603', 'NGC 3603', 'starforming', 168.80, -61.26, '20,000 ly',
    'A giant H II region packing some of the densest concentrations of massive stars in the galaxy.',
    [['Type', 'H II region'], ['Stars', 'Very massive']]),

  // ---- Extreme stars ----
  P('Betelgeuse', 'Betelgeuse', 'star', 88.793, 7.407, '548 ly',
    'A red supergiant so large it would swallow Jupiter\'s orbit. It dimmed dramatically in 2019–20 and will explode as a supernova, astronomically soon.',
    [['Type', 'Red supergiant'], ['Radius', '~760 R☉'], ['Fate', 'Supernova']]),
  P('Eta Carinae', 'Eta Carinae', 'star', 161.265, -59.684, '7,500 ly',
    'A monstrous, unstable binary that staged a "Great Eruption" in the 1840s, briefly becoming the second-brightest star in the sky.',
    [['Type', 'Luminous blue variable'], ['Mass', '~100+ M☉']]),
  P('VY CMa', 'VY Canis Majoris', 'star', 110.74, -25.77, '3,840 ly',
    'One of the largest known stars: a red hypergiant roughly 1,400 times the Sun\'s radius, shedding huge amounts of mass.',
    [['Type', 'Red hypergiant'], ['Radius', '~1,420 R☉']]),
  P('R136a1', 'R136a1', 'star', 84.675, -69.10, '160,000 ly',
    'The most massive star known, blazing in the Tarantula Nebula at millions of times the Sun\'s luminosity.',
    [['Mass', '~196 M☉'], ['Most massive star', 'yes']]),
  P('Sirius B', 'Sirius B', 'star', 101.287, -16.716, '8.6 ly',
    'The nearest white dwarf: an Earth-sized stellar ember as massive as the Sun, orbiting brilliant Sirius A.',
    [['Type', 'White dwarf'], ['Density', 'Extreme']]),
  P('Algol', 'Algol (Demon Star)', 'star', 47.042, 40.956, '90 ly',
    'The prototype eclipsing binary: every 2.87 days a dim companion passes in front, visibly dimming the star.',
    [['Type', 'Eclipsing binary'], ['Period', '2.87 d']]),
  P('SS 433', 'SS 433', 'star', 287.957, 4.98, '18,000 ly',
    'A microquasar firing precessing jets at a quarter the speed of light, the first known "Galactic" relativistic-jet source.',
    [['Type', 'Microquasar'], ['Jets', '0.26c']]),

  // ---- Exoplanet systems ----
  P('TRAPPIST-1', 'TRAPPIST-1', 'exoplanet', 346.62, -5.04, '40 ly',
    'A cool red dwarf with seven Earth-sized planets, three in the habitable zone, the richest nearby system for studying rocky worlds.',
    [['Planets', '7'], ['Habitable zone', '3 planets']]),
  P('51 Pegasi', '51 Pegasi', 'exoplanet', 344.366, 20.769, '50 ly',
    'Host of 51 Peg b (1995), the first exoplanet found around a Sun-like star, a discovery that won the 2019 Nobel Prize.',
    [['First exoplanet (Sun-like)', '1995'], ['Planet', 'Hot Jupiter']]),
  P('Kepler-90', 'Kepler-90', 'exoplanet', 285.43, 49.31, '2,840 ly',
    'A Sun-like star with eight known planets, tying our own Solar System for the most planets in one system.',
    [['Planets', '8'], ['Ties', 'Solar System']]),
  P('HD 209458', 'HD 209458 (Osiris)', 'exoplanet', 330.795, 18.884, '159 ly',
    'The first exoplanet seen transiting its star and the first with a detected atmosphere, evaporating into a comet-like tail.',
    [['First transit', '1999'], ['Atmosphere', 'Detected']]),
  P('Proxima Centauri', 'Proxima Centauri', 'exoplanet', 217.429, -62.679, '4.24 ly',
    'The closest star to the Sun, hosting Proxima b, a roughly Earth-mass planet in its habitable zone, the nearest such world.',
    [['Planets', '2+'], ['Nearest exoplanet', 'Proxima b']]),

  // ---- Gravitational-wave events (approximate sky positions) ----
  P('GW150914', 'GW150914', 'gw', 112.0, -70.0, '1.3 Gly',
    'The first direct detection of gravitational waves (2015): the merger of two black holes ~1.3 billion years ago, confirming Einstein and launching a new astronomy.',
    [['Source', '36+29 M☉ black holes'], ['First detection', '2015']]),
  P('GW170817', 'GW170817', 'gw', 197.45, -23.38, '130 Mly',
    'The first neutron-star merger seen in both gravitational waves and light (in galaxy NGC 4993): a kilonova that forged heavy elements like gold.',
    [['Source', 'Neutron-star merger'], ['Made', 'Heavy elements']]),
  P('GW190521', 'GW190521', 'gw', 192.0, 35.0, '~17 Gly',
    'The merger that produced an intermediate-mass black hole of ~142 M☉, bridging stellar and supermassive scales.',
    [['Result', '~142 M☉ black hole'], ['Class', 'Intermediate-mass']]),
];
