// Catalogue of real astrophysical phenomena — pulsars, magnetars, black holes,
// quasars/AGN, supernova remnants, nebulae, star-forming regions, exotic stars,
// exoplanet systems and gravitational-wave events. Each entry carries a short
// documentation blurb and key facts and is positioned by RA/Dec (degrees) and a
// distance string. All data is from public catalogues (no licensed assets).
// ra: right ascension in DEGREES (0–360). dec: declination in degrees (−90..90).

export const PHENOM_CATS = {
  pulsar:      { label: 'Pulsars',                color: '#7fe0c8' },
  magnetar:    { label: 'Magnetars',             color: '#ff8f6b' },
  blackhole:   { label: 'Black holes',           color: '#c88bff' },
  quasar:      { label: 'Quasars & AGN',         color: '#ffd27f' },
  snr:         { label: 'Supernova remnants',    color: '#ff9fb0' },
  nebula:      { label: 'Nebulae',               color: '#e08fd4' },
  starforming: { label: 'Star-forming regions',  color: '#9fd4ff' },
  star:        { label: 'Extreme stars',         color: '#ffe9a8' },
  exoplanet:   { label: 'Exoplanet systems',     color: '#9fffb0' },
  gw:          { label: 'Gravitational waves',   color: '#b0c0ff' },
  radio:       { label: 'Radio transients',      color: '#d8ff7a' },
  grb:         { label: 'Gamma-ray bursts',      color: '#ff7ad9' },
};

// helper to keep entries terse: [id, name, cat, raDeg, dec, dist, doc, facts]
const P = (id, name, cat, ra, dec, dist, doc, facts) => ({ id, name, cat, ra, dec, dist, doc, facts });

export const PHENOMENA = [
  // ---- Pulsars (rotating neutron stars) ----
  P('PSR B0531+21', 'Crab Pulsar', 'pulsar', 83.633, 22.014, '6,500 ly',
    'The neutron-star heart of the Crab Nebula, born in the supernova seen in 1054 AD. It spins 30 times a second and powers the entire nebula.',
    [['Spin period', '33.5 ms'], ['Type', 'Young pulsar'], ['Remnant of', 'SN 1054']]),
  P('PSR B0833-45', 'Vela Pulsar', 'pulsar', 128.836, -45.176, '960 ly',
    'One of the brightest radio pulsars and a famous gamma-ray source, sitting inside the Vela supernova remnant.',
    [['Spin period', '89 ms'], ['Age', '~11,000 yr']]),
  P('PSR B1919+21', 'LGM-1', 'pulsar', 290.0, 21.88, '2,300 ly',
    'The very first pulsar ever detected, found by Jocelyn Bell Burnell in 1967. Its clockwork pulses were briefly nicknamed "Little Green Men".',
    [['Spin period', '1.337 s'], ['Discovered', '1967']]),
  P('PSR B1257+12', 'Lich', 'pulsar', 194.583, 12.68, '2,300 ly',
    'A millisecond pulsar orbited by the first exoplanets ever confirmed (1992): three small worlds circling a dead star.',
    [['Spin period', '6.2 ms'], ['Planets', '3'], ['First exoplanets', '1992']]),
  P('PSR B1937+21', 'First Millisecond Pulsar', 'pulsar', 294.911, 21.583, '11,700 ly',
    'The first millisecond pulsar discovered (1982); it spins 642 times per second, rivalling the precision of atomic clocks.',
    [['Spin period', '1.558 ms'], ['Spins/sec', '642']]),
  P('PSR B1913+16', 'Hulse–Taylor Binary', 'pulsar', 288.0, 16.11, '21,000 ly',
    'A pulsar in a binary with another neutron star. Its decaying orbit gave the first proof that gravitational waves exist, a 1993 Nobel Prize.',
    [['Spin period', '59 ms'], ['Proved', 'Gravitational waves']]),
  P('PSR J0737-3039', 'Double Pulsar', 'pulsar', 114.464, -30.66, '2,400 ly',
    'The only known system of two pulsars orbiting each other, a unique natural laboratory for testing general relativity.',
    [['Periods', '23 ms & 2.8 s'], ['Pulsars', '2']]),
  P('PSR J0437-4715', 'Nearest Millisecond Pulsar', 'pulsar', 69.316, -47.252, '510 ly',
    'The closest and brightest millisecond pulsar, a precision timing target with a white-dwarf companion.',
    [['Spin period', '5.76 ms'], ['Nearest of its kind', 'yes']]),
  P('Geminga', 'Geminga', 'pulsar', 98.476, 17.77, '815 ly',
    'A nearby gamma-ray pulsar that is nearly radio-silent, one of the brightest sources in the gamma-ray sky.',
    [['Spin period', '237 ms'], ['Type', 'Gamma-ray pulsar']]),
  P('PSR J1748-2446ad', 'Fastest Pulsar', 'pulsar', 267.02, -24.78, '18,000 ly',
    'The fastest-spinning neutron star known, in the globular cluster Terzan 5. Its equator moves at a quarter of the speed of light: 716 rotations every second.',
    [['Spin period', '1.396 ms'], ['Spins/sec', '716'], ['Cluster', 'Terzan 5']]),
  P('PSR B0329+54', 'PSR B0329+54', 'pulsar', 53.25, 54.58, '3,300 ly',
    'The brightest radio pulsar in the northern sky and a favourite "first pulsar" for radio-astronomy students: its heartbeat is easy to hear on a small dish.',
    [['Spin period', '714 ms'], ['Northern sky', 'Brightest pulsar']]),
  P('PSR J0740+6620', 'Most Massive Neutron Star', 'pulsar', 115.0, 66.34, '3,700 ly',
    'The heaviest precisely-weighed neutron star, 2.08 solar masses packed into a city-sized sphere, right at the edge of what nuclear matter can support before collapsing into a black hole.',
    [['Mass', '2.08 M☉'], ['Spin period', '2.89 ms']]),
  P('PSR B1957+20', 'Black Widow Pulsar', 'pulsar', 299.90, 20.80, '6,500 ly',
    'A millisecond pulsar slowly vaporising its tiny companion star with its wind of radiation, hence the name. In a few hundred million years the companion will be gone entirely.',
    [['Spin period', '1.607 ms'], ['Companion', 'Being evaporated']]),
  P('RX J1856', 'RX J1856.5−3754', 'pulsar', 284.13, -37.90, '~400 ly',
    'The nearest known neutron star: a lone, silent ember drifting through the solar neighbourhood, seen only by the dim heat of its million-degree surface.',
    [['Type', 'Isolated neutron star'], ['Nearest known', 'yes']]),
  P('PSR J2144-3933', 'Slowest Pulsar', 'pulsar', 326.05, -39.55, '~590 ly',
    'The slowest-spinning radio pulsar known, taking 8.5 seconds per turn. By every textbook it should be too slow to shine at all — yet it pulses on, a standing challenge to theory.',
    [['Spin period', '8.51 s'], ['Should be dead', 'By theory, yes']]),
  P('PSR J0540-6919', "The Crab's Twin", 'pulsar', 85.05, -69.33, '163,000 ly',
    'A near-copy of the Crab Pulsar in the Large Magellanic Cloud — young, fast, wrapped in its own supernova remnant — and the first pulsar detected in gamma rays from outside our galaxy.',
    [['Spin period', '50 ms'], ['Galaxy', 'LMC']]),
  P('PSR J0952-0607', 'PSR J0952−0607', 'pulsar', 148.03, -6.12, '~20,000 ly',
    'A black-widow pulsar that has eaten so much of its companion it has grown to 2.35 solar masses — the heaviest neutron star candidate known, teetering on the edge of collapse.',
    [['Mass', '~2.35 M☉'], ['Spin', '707 /s'], ['Heaviest candidate', 'yes']]),
  P('Cen X-3', 'Centaurus X-3', 'pulsar', 170.31, -60.62, '~25,000 ly',
    'The first X-ray pulsar ever discovered (1971): a neutron star in a binary, flashing in X-rays every 4.8 seconds as it devours its giant companion.',
    [['First X-ray pulsar', '1971'], ['Pulse', '4.8 s']]),
  P('Her X-1', 'Hercules X-1', 'pulsar', 254.46, 35.34, '21,000 ly',
    'An X-ray pulsar whose warped accretion disk wobbles with a 35-day rhythm, periodically hiding the neutron star — a lighthouse behind a tilting curtain.',
    [['Pulse', '1.24 s'], ['Disk precession', '35 d']]),
  P('Vela X-1', 'Vela X-1', 'pulsar', 135.53, -40.55, '6,200 ly',
    'The archetypal wind-fed X-ray pulsar: a heavy neutron star ploughing through the gale shed by its blue supergiant companion, flaring as it swallows clumps of wind.',
    [['Type', 'Wind-fed X-ray binary'], ['NS mass', '~2 M☉']]),
  P('PSR B1509-58', 'Hand of God Pulsar', 'pulsar', 228.48, -59.14, '17,000 ly',
    'A young pulsar whose particle wind sculpts an X-ray nebula shaped uncannily like an outstretched hand, reaching for a neighbouring gas cloud.',
    [['Nebula', 'MSH 15−52 "the Hand"'], ['Spin period', '150 ms']]),
  P('PSR J1747-2958', 'The Mouse', 'pulsar', 266.82, -29.97, '~16,000 ly',
    'A runaway pulsar tearing through space so fast its wind nebula streams behind it like a mouse\'s tail — a shock-wave portrait of a neutron star in flight.',
    [['Speed', '~600 km/s'], ['Tail', 'Light-years long']]),
  P('PSR J1023+0038', 'PSR J1023+0038', 'pulsar', 155.95, 0.64, '4,400 ly',
    'A shape-shifting pulsar caught switching between two lives: some years a radio pulsar, other years an X-ray binary feeding from its companion — the missing link between the two.',
    [['Type', 'Transitional pulsar'], ['States', 'Radio ↔ accreting']]),
  P('PSR B0656+14', 'PSR B0656+14', 'pulsar', 104.95, 14.24, '940 ly',
    'One of the "Three Musketeers" of nearby gamma-ray pulsars, sitting inside the faint Monogem Ring — the remnant of the explosion that made it.',
    [['Age', '~110,000 yr'], ['Remnant', 'Monogem Ring']]),

  // ---- Magnetars (ultra-magnetic neutron stars) ----
  P('SGR 1806-20', 'SGR 1806−20', 'magnetar', 272.16, -20.41, '~42,000 ly',
    'The most magnetic object known. In 2004 it released a giant flare that briefly outshone the full Moon in gamma rays and disturbed Earth\'s ionosphere from across the galaxy.',
    [['Field', '~2×10¹¹ T'], ['2004 flare', 'Brightest ever']]),
  P('SGR 1900+14', 'SGR 1900+14', 'magnetar', 286.8, 9.32, '~20,000 ly',
    'A magnetar whose 1998 giant flare forced satellites to safe-mode and revealed the soft-gamma-repeater class.',
    [['Spin period', '5.2 s'], ['Giant flare', '1998']]),
  P('1E 2259+586', '1E 2259+586', 'magnetar', 345.28, 58.88, '~10,000 ly',
    'An anomalous X-ray pulsar in the supernova remnant CTB 109, a textbook magnetar.',
    [['Spin period', '7 s'], ['In SNR', 'CTB 109']]),
  P('Swift J1818', 'Swift J1818.0−1607', 'magnetar', 274.51, -16.13, '~14,000 ly',
    'One of the fastest-spinning magnetars and a rare radio-loud one, a likely very young neutron star.',
    [['Spin period', '1.36 s'], ['Age', '~470 yr']]),
  P('XTE J1810-197', 'XTE J1810−197', 'magnetar', 272.46, -19.73, '~10,000 ly',
    'The first magnetar found to emit radio pulses, switching its radio emission on and off over years.',
    [['Spin period', '5.5 s'], ['Radio', 'Transient']]),
  P('SGR 0525-66', 'SGR 0525−66', 'magnetar', 81.50, -66.08, '163,000 ly',
    'The first soft gamma repeater ever recognised: its colossal flare on 5 March 1979 lit up every gamma-ray detector in the solar system and started magnetar science.',
    [['Giant flare', '1979'], ['Galaxy', 'LMC'], ['First of its class', 'yes']]),
  P('SGR 1935+2154', 'SGR 1935+2154', 'magnetar', 293.75, 21.90, '~30,000 ly',
    'In April 2020 this magnetar fired off a radio blast so intense it solved a mystery: fast radio bursts, seen for years from other galaxies, can come from magnetars.',
    [['FRB 200428', 'First galactic FRB'], ['Spin period', '3.2 s']]),
  P('CXOU J1647-45', 'Westerlund 1 Magnetar', 'magnetar', 251.79, -45.87, '~13,000 ly',
    'A magnetar born from a star of at least forty solar masses — heavy enough that it should have collapsed into a black hole. That a neutron star survived is a puzzle about how giants die.',
    [['Progenitor', '≥40 M☉'], ['Expected outcome', 'Black hole'], ['Cluster', 'Westerlund 1']]),
  P('4U 0142+61', '4U 0142+61', 'magnetar', 26.59, 61.75, '~13,000 ly',
    'The magnetar found wearing a debris disk — rubble from the supernova that made it, raising the strange possibility of planets forming around a dead star\'s corpse.',
    [['Debris disk', 'Found 2006'], ['Spin period', '8.7 s']]),

  // ---- Black holes (stellar-mass & X-ray binaries) ----
  P('Cygnus X-1', 'Cygnus X-1', 'blackhole', 299.59, 35.20, '7,200 ly',
    'The first object widely accepted as a black hole. It pulls gas from a blue supergiant companion, and was the subject of a famous Hawking–Thorne bet.',
    [['Mass', '~21 M☉'], ['Companion', 'Blue supergiant'], ['Confirmed', '1971']]),
  P('V404 Cygni', 'V404 Cygni', 'blackhole', 306.02, 33.87, '7,800 ly',
    'A black-hole binary that erupts every few decades; its 2015 outburst was one of the brightest X-ray events of the era.',
    [['Mass', '~9 M☉'], ['Outburst', '2015']]),
  P('GRS 1915+105', 'GRS 1915+105', 'blackhole', 288.80, 10.95, '36,000 ly',
    'A microquasar firing jets of plasma at apparently faster-than-light (superluminal) speeds, an illusion of relativistic motion.',
    [['Mass', '~12 M☉'], ['Jets', 'Superluminal']]),
  P('GRO J1655-40', 'GRO J1655−40', 'blackhole', 253.50, -39.85, '11,000 ly',
    'A microquasar whose spinning black hole drags spacetime around it (frame dragging), measured from its X-ray flicker.',
    [['Mass', '~6.3 M☉'], ['Spin', 'Rapid']]),
  P('A0620-00', 'A0620−00', 'blackhole', 95.68, -0.35, '3,500 ly',
    'The nearest black hole that is actively feeding: an X-ray binary quietly pulling gas from an orange dwarf companion.',
    [['Mass', '~6.6 M☉'], ['Nearest X-ray binary BH', 'yes']]),
  P('Gaia BH1', 'Gaia BH1', 'blackhole', 262.17, -0.58, '1,560 ly',
    'The nearest known black hole, discovered in 2022 from the wobble of the Sun-like star that orbits it. Completely dormant: it emits nothing, and only gravity gives it away.',
    [['Mass', '~9.6 M☉'], ['Nearest BH', '1,560 ly'], ['State', 'Dormant']]),
  P('MAXI J1820+070', 'MAXI J1820+070', 'blackhole', 275.09, 7.19, '~10,000 ly',
    'A black hole whose 2018 outburst grew bright enough for amateur telescopes, and whose flickering let astronomers film matter spiralling in almost frame by frame.',
    [['Mass', '~8 M☉'], ['Outburst', '2018']]),
  P('M87*', 'M87* — First Black Hole Imaged', 'blackhole', 187.706, 12.391, '53 Mly',
    'The first black hole humanity ever photographed: the Event Horizon Telescope\'s 2019 image of a glowing ring around darkness, 6.5 billion solar masses at the heart of galaxy M87.',
    [['Mass', '6.5 billion M☉'], ['Imaged', '2019 (EHT)'], ['Jet', '5,000 ly long']]),
  P('Gaia BH3', 'Gaia BH3', 'blackhole', 294.83, 14.93, '1,930 ly',
    'The most massive stellar black hole known in our galaxy: 33 solar masses, found in 2024 from an old star wobbling around apparently nothing. It formed from a nearly metal-free ancient star.',
    [['Mass', '33 M☉'], ['Found', '2024 (Gaia)'], ['State', 'Dormant']]),
  P('Cygnus X-3', 'Cygnus X-3', 'blackhole', 308.11, 40.96, '24,000 ly',
    'A compact object locked in a 4.8-hour orbit with a Wolf–Rayet star, so tight it orbits inside its companion\'s wind. Whether the eater is a black hole or neutron star is still debated.',
    [['Orbit', '4.8 hr'], ['Companion', 'Wolf–Rayet'], ['Nature', 'BH or NS — debated']]),
  P('GX 339-4', 'GX 339−4', 'blackhole', 255.71, -48.79, '~26,000 ly',
    'The workhorse of black-hole astronomy: it erupts every few years and cycles through every known accretion state, making it the reference against which other black holes are read.',
    [['Mass', '~9 M☉'], ['Outbursts', 'Every few years']]),
  P('XTE J1118+480', 'XTE J1118+480', 'blackhole', 169.55, 48.04, '5,700 ly',
    'A black hole living in the galaxy\'s halo, far above the disk where stars are born — flung there by the kick of the very supernova that created it.',
    [['Mass', '~7 M☉'], ['Home', 'Galactic halo']]),
  P('V4641 Sgr', 'V4641 Sagittarii', 'blackhole', 274.84, -25.41, '~20,000 ly',
    'A black hole that produced the fastest apparent jet ever seen from a stellar object — a 1999 flare so violent it briefly rivalled the brightest X-ray sources in the sky.',
    [['Jet', 'Apparent >9c'], ['Flare', '1999']]),
  P('OGLE BH', 'OB110462 — Lone Black Hole', 'blackhole', 267.92, -29.89, '~5,000 ly',
    'The first isolated black hole ever detected: no companion, no glow — found only because its gravity briefly magnified a background star as it drifted past. Millions more wander unseen.',
    [['Found by', 'Microlensing (2022)'], ['Companion', 'None']]),
  P('HLX-1', 'HLX-1', 'blackhole', 17.62, -46.07, '290 Mly',
    'The best candidate for a long-sought intermediate-mass black hole: ~20,000 solar masses at the edge of another galaxy, possibly the stripped heart of a swallowed dwarf galaxy.',
    [['Mass', '~20,000 M☉'], ['Class', 'Intermediate — the missing size']]),
  P('LMC X-1', 'LMC X-1', 'blackhole', 84.91, -69.74, '163,000 ly',
    'A black-hole binary in the Large Magellanic Cloud, devouring a hot massive companion.',
    [['Mass', '~10.9 M☉'], ['Galaxy', 'LMC']]),
  P('Sgr A*', 'Sagittarius A*', 'blackhole', 266.417, -29.008, '26,700 ly',
    'The supermassive black hole at the centre of the Milky Way, imaged by the Event Horizon Telescope in 2022. Four million times the Sun\'s mass.',
    [['Mass', '4.3 million M☉'], ['Imaged', '2022 (EHT)']]),

  // ---- Quasars & active galactic nuclei ----
  P('3C 273', '3C 273', 'quasar', 187.278, 2.052, '2.4 Gly',
    'The first quasar ever identified (1963) and the optically brightest in our sky: a supermassive black hole outshining its whole galaxy.',
    [['Type', 'Quasar'], ['First identified', '1963'], ['Luminosity', '~4×10¹² L☉']]),
  P('TON 618', 'TON 618', 'quasar', 184.36, 31.73, '10.4 Gly',
    'Home to one of the most massive black holes known, tens of billions of solar masses, blazing across the early universe.',
    [['BH mass', '~40 billion M☉'], ['Type', 'Hyperluminous quasar']]),
  P('OJ 287', 'OJ 287', 'quasar', 133.70, 20.11, '3.5 Gly',
    'A blazar containing a binary supermassive black hole; the smaller hole plunges through the larger one\'s disk every ~12 years, causing bright flares.',
    [['Type', 'Blazar (binary)'], ['Flare cycle', '~12 yr']]),
  P('Mrk 421', 'Markarian 421', 'quasar', 166.114, 38.21, '397 Mly',
    'One of the closest and best-studied blazars, with a jet pointed almost straight at Earth; a bright TeV gamma-ray source.',
    [['Type', 'Blazar'], ['Jet', 'Aimed at us']]),
  P('M77', 'NGC 1068 (Messier 77)', 'quasar', 40.67, -0.01, '47 Mly',
    'A nearby Seyfert galaxy with an obscured active nucleus, a recent source of high-energy cosmic neutrinos.',
    [['Type', 'Seyfert galaxy'], ['Neutrinos', 'Detected']]),
  P('3C 48', '3C 48', 'quasar', 24.42, 33.16, '3.9 Gly',
    'The first quasar ever catalogued (1960): a "star" that turned out to be the blazing nucleus of a distant galaxy, years before anyone understood what quasars were.',
    [['Catalogued', '1960'], ['Type', 'Quasar']]),
  P('ULAS J1342', 'ULAS J1342+0928', 'quasar', 205.53, 9.48, '13.1 Gly',
    'One of the most distant quasars known, shining from when the universe was only 690 million years old — a billion-solar-mass black hole that grew impossibly fast.',
    [['Redshift', 'z = 7.54'], ['Universe age then', '~690 Myr']]),
  P('3C 279', '3C 279', 'quasar', 194.05, -5.79, '5.2 Gly',
    'The blazar whose jet first appeared to move faster than light (1971) — an illusion of material racing almost straight at us, but a shock at the time.',
    [['Type', 'Blazar'], ['Superluminal motion', 'First seen']]),
  P('BL Lac', 'BL Lacertae', 'quasar', 330.68, 42.28, '900 Mly',
    'Once catalogued as a variable star, actually the naked nucleus of an active galaxy with a jet aimed at Earth. It lends its name to the whole "BL Lac" class.',
    [['Type', 'Blazar prototype'], ['Mistaken for', 'A star']]),
  P('APM 08279', 'APM 08279+5255', 'quasar', 127.92, 52.75, '12 Gly',
    'A gravitationally-lensed quasar holding the largest water reservoir ever found: vapour equal to 140 trillion Earth oceans, orbiting a black hole in the early universe.',
    [['Water', '140 trillion oceans'], ['Lensed', 'yes']]),
  P('Cygnus A', 'Cygnus A', 'quasar', 299.87, 40.73, '760 Mly',
    'The prototype radio galaxy: two jets from its central black hole inflate lobes of radio-bright plasma spanning half a million light-years, dwarfing the galaxy that made them.',
    [['Type', 'Radio galaxy'], ['Lobes', '~500,000 ly across']]),
  P('J0529-4351', 'J0529−4351', 'quasar', 82.32, -43.86, '12.1 Gly',
    'The most luminous object known in the universe: a quasar shining like 500 trillion Suns, whose black hole swallows roughly one Sun\'s worth of matter every day.',
    [['Luminosity', '~5×10¹⁴ L☉'], ['Feeding rate', '~1 M☉/day'], ['Confirmed', '2024']]),
  P('NGC 4151', 'NGC 4151 (Eye of Sauron)', 'quasar', 182.64, 39.41, '62 Mly',
    'One of the nearest galaxies with an actively feeding supermassive black hole — its glowing core and dark dust ring earned it the nickname "Eye of Sauron".',
    [['Type', 'Seyfert galaxy'], ['BH mass', '~40 million M☉']]),
  P('Mrk 501', 'Markarian 501', 'quasar', 253.47, 39.76, '456 Mly',
    'A blazar whose gamma-ray flares flicker in minutes — light-crossing arguments say the emitting region is barely larger than the solar system, right beside a billion-sun black hole.',
    [['Type', 'TeV blazar'], ['Flares', 'Minute-scale']]),
  P('PKS 2155-304', 'PKS 2155−304', 'quasar', 329.72, -30.23, '1.5 Gly',
    'The brightest blazar of the southern sky in high-energy gamma rays, whose 2006 outburst remains one of the most violent flaring episodes ever recorded.',
    [['Type', 'Blazar'], ['2006 flare', 'Historic']]),
  P('Twin Quasar', 'Twin Quasar (Q0957+561)', 'quasar', 150.34, 55.90, '8.7 Gly',
    'The first gravitational lens ever found (1979): one quasar seen twice, its light split into two images by a galaxy in the way — Einstein\'s prediction made visible.',
    [['First lens', '1979'], ['Images', '2 of the same quasar']]),
  P('Einstein Cross', 'Einstein Cross', 'quasar', 340.13, 3.36, '8 Gly',
    'A single quasar smeared into four images arranged in a perfect cross around a foreground galaxy — the textbook picture of gravitational lensing.',
    [['Images', '4 of one quasar'], ['Lens', 'Foreground galaxy']]),
  P('NGC 1275', 'NGC 1275 (Perseus A)', 'quasar', 49.95, 41.51, '240 Mly',
    'The black hole at the heart of the Perseus cluster blows bubbles into the surrounding hot gas — pressure waves tuned to a B-flat 57 octaves below middle C, the deepest note known.',
    [['Note', 'B♭, 57 octaves down'], ['Cluster', 'Perseus']]),
  P('Mrk 231', 'Markarian 231', 'quasar', 194.06, 56.87, '580 Mly',
    'The nearest quasar — the still-blazing core of two galaxies in mid-collision, wrapped in the wreckage of the merger that lit it.',
    [['Nearest quasar', 'yes'], ['State', 'Galaxy merger']]),
  P('S5 0014+81', 'S5 0014+81', 'quasar', 4.29, 81.58, '12.1 Gly',
    'Host of one of the largest black holes ever measured — around forty billion solar masses, a horizon that would swallow our solar system hundreds of times over.',
    [['BH mass', '~40 billion M☉'], ['Type', 'Blazar']]),

  // ---- Supernova remnants ----
  P('Cas A', 'Cassiopeia A', 'snr', 350.85, 58.815, '11,000 ly',
    'The expanding debris of a star that exploded ~340 years ago, the brightest radio source beyond the Sun and a JWST showpiece.',
    [['Age', '~340 yr'], ['Type', 'SNR']]),
  P('Tycho', "Tycho's Supernova Remnant", 'snr', 6.32, 64.14, '~10,000 ly',
    'Remnant of the bright supernova Tycho Brahe recorded in 1572, a Type Ia explosion that reshaped European astronomy.',
    [['Event', 'SN 1572'], ['Type', 'Ia']]),
  P('Kepler', "Kepler's Supernova Remnant", 'snr', 262.67, -21.49, '~20,000 ly',
    'Remnant of SN 1604, the most recent naked-eye supernova seen in the Milky Way, observed by Johannes Kepler.',
    [['Event', 'SN 1604'], ['Last galactic SN seen', 'yes']]),
  P('Veil', 'Veil Nebula (Cygnus Loop)', 'snr', 312.75, 30.72, '2,400 ly',
    'Delicate filaments of a supernova that detonated ~10,000–20,000 years ago, spanning six full Moons of sky.',
    [['Age', '~10–20 kyr'], ['Type', 'SNR']]),
  P('SN 1006', 'SN 1006 Remnant', 'snr', 225.59, -41.94, '7,200 ly',
    'Remnant of the brightest stellar event in recorded history (1006 AD), bright enough to read by at night.',
    [['Event', 'SN 1006'], ['Brightest SN recorded', 'yes']]),
  P('G1.9+0.3', 'G1.9+0.3', 'snr', 267.19, -27.17, '25,000 ly',
    'The youngest supernova remnant in the Milky Way: the star exploded only ~150 years ago, but interstellar dust hid the flash from every telescope on Earth.',
    [['Age', '~150 yr'], ['Youngest in galaxy', 'yes'], ['Seen at the time', 'No — hidden by dust']]),
  P('RCW 86', 'RCW 86 (SN 185)', 'snr', 220.75, -62.50, '8,200 ly',
    'The remnant of the oldest recorded supernova: Chinese astronomers logged the "guest star" of 185 AD, and this glowing shell is what remains eighteen centuries later.',
    [['Event', 'SN 185'], ['Oldest recorded SN', 'yes']]),
  P('W49B', 'W49B', 'snr', 287.79, 9.11, '26,000 ly',
    'A barrel-shaped remnant that may be the debris of a rare jet-driven explosion — the nearest thing to a gamma-ray-burst relic in our own galaxy.',
    [['Shape', 'Jet-driven?'], ['Age', '~1,000 yr']]),
  P('Puppis A', 'Puppis A', 'snr', 126.0, -43.0, '7,000 ly',
    'A bright X-ray remnant whose neutron star was kicked so hard by the explosion it now crosses space at over 1,000 km/s — the "Cosmic Cannonball".',
    [['Age', '~3,700 yr'], ['Neutron star', '>1,000 km/s']]),
  P('IC 443', 'Jellyfish Nebula', 'snr', 94.30, 22.52, '5,000 ly',
    'A supernova remnant draped like a jellyfish across Gemini, its tendrils glowing where the blast wave slams into a neighbouring molecular cloud.',
    [['Type', 'SNR'], ['Age', '~30,000 yr']]),
  P('Simeis 147', 'Spaghetti Nebula', 'snr', 84.75, 27.83, '3,000 ly',
    'An ancient remnant unravelled into a sphere of fine red filaments three full Moons wide — forty thousand years of a shockwave slowly coming apart.',
    [['Type', 'SNR'], ['Age', '~40,000 yr'], ['Span', '~160 ly']]),
  P('Pa 30', 'Pa 30 (SN 1181)', 'snr', 13.30, 67.50, '~7,500 ly',
    'The remnant of the "guest star" of 1181 AD — and the strangest one known: at its centre sits a zombie star, the survivor of two white dwarfs that collided and failed to fully explode.',
    [['Event', 'SN 1181'], ['Centre', 'Surviving zombie star'], ['Winds', '16,000 km/s']]),
  P('GK Persei', 'GK Persei (Nova 1901)', 'snr', 52.80, 43.90, '1,500 ly',
    'The "Firework Nebula": debris from the brilliant nova of 1901 still expanding a century later — a white dwarf\'s surface explosion caught mid-bloom.',
    [['Event', 'Nova Persei 1901'], ['Type', 'Nova remnant']]),
  P('G292.0+1.8', 'G292.0+1.8', 'snr', 171.15, -59.27, '20,000 ly',
    'A textbook oxygen-rich remnant: shredded stellar guts flung across thirty light-years, still glowing with the oxygen the dead star forged — the stuff future planets breathe.',
    [['Type', 'Oxygen-rich SNR'], ['Age', '~3,000 yr']]),
  P('RX J1713-3946', 'RX J1713.7−3946', 'snr', 258.46, -39.77, '~3,000 ly',
    'The brightest supernova remnant in very-high-energy gamma rays, and a prime suspect in a century-old mystery: where cosmic rays come from.',
    [['TeV source', 'Brightest SNR'], ['Role', 'Cosmic-ray accelerator']]),

  // ---- Nebulae (emission, planetary, dark) ----
  P('Helix', 'Helix Nebula', 'nebula', 337.41, -20.84, '655 ly',
    'One of the closest planetary nebulae: the glowing shroud a Sun-like star casts off as it dies, often called the "Eye of God".',
    [['Type', 'Planetary nebula'], ['Central star', 'White dwarf']]),
  P('Cat\'s Eye', "Cat's Eye Nebula", 'nebula', 269.64, 66.63, '3,300 ly',
    'An intricate planetary nebula of nested shells and jets, revealing the complex death throes of a dying star.',
    [['Type', 'Planetary nebula'], ['Structure', 'Nested shells']]),
  P('Horsehead', 'Horsehead Nebula', 'nebula', 85.24, -2.46, '1,375 ly',
    'A dark column of dust silhouetted against glowing hydrogen in Orion, one of the most recognisable shapes in the sky.',
    [['Type', 'Dark nebula'], ['In', 'Orion']]),
  P('NGC 7000', 'North America Nebula', 'nebula', 314.75, 44.52, '2,590 ly',
    'A vast emission nebula whose shape mirrors the continent of North America, lit by hot young stars.',
    [['Type', 'Emission nebula'], ['Size', '~100 ly']]),
  P('Rosette', 'Rosette Nebula', 'nebula', 97.95, 4.95, '5,200 ly',
    'A flower-shaped emission nebula with a young star cluster carving a cavity at its heart.',
    [['Type', 'Emission nebula'], ['Cluster', 'NGC 2244']]),
  P('NGC 2392', 'Eskimo Nebula', 'nebula', 112.29, 20.91, '~6,500 ly',
    'A double-shelled planetary nebula that looks like a face inside a furry hood: a dying star\'s outer layers streaming past an older ring of gas.',
    [['Type', 'Planetary nebula'], ['Shells', 'Two']]),
  P('NGC 6302', 'Butterfly Nebula', 'nebula', 258.43, -37.10, '~3,800 ly',
    'Wings of glowing gas spread by one of the hottest dying stars known, around 220,000 degrees, hidden inside a doughnut of dust at the centre.',
    [['Type', 'Bipolar planetary'], ['Central star', '~220,000 K']]),
  P('Red Rectangle', 'Red Rectangle Nebula', 'nebula', 94.99, -10.64, '2,300 ly',
    'A bizarre X-shaped nebula with rungs like a ladder, sculpted by a binary star. Its unexplained red glow is one of the oldest puzzles in astro-spectroscopy.',
    [['Shape', 'X with rungs'], ['Red glow', 'Unexplained']]),
  P('Boomerang', 'Boomerang Nebula', 'nebula', 191.19, -54.52, '5,000 ly',
    'The coldest known place in the universe: gas expanding so fast it has chilled to one degree above absolute zero, colder than the afterglow of the Big Bang itself.',
    [['Temperature', '~1 K'], ['Coldest known place', 'yes']]),
  P('Coalsack', 'Coalsack Nebula', 'nebula', 192.5, -62.5, '590 ly',
    'The great dark cloud beside the Southern Cross, a hole punched in the Milky Way to the naked eye. In Andean astronomy it forms the head of a celestial llama.',
    [['Type', 'Dark nebula'], ['Visible', 'Naked eye']]),
  P('NGC 2264', 'Cone Nebula', 'nebula', 100.25, 9.88, '2,700 ly',
    'A dark pillar of gas seven light-years tall, sculpted beneath the Christmas Tree star cluster by the radiation of newborn stars above it.',
    [['Height', '~7 ly'], ['Cluster', 'Christmas Tree']]),
  P('NGC 6888', 'Crescent Nebula', 'nebula', 303.0, 38.35, '5,000 ly',
    'A shell blown by a dying Wolf–Rayet star ramming into the wind it shed ages earlier as a red giant — a star colliding with its own past.',
    [['Type', 'Wolf–Rayet shell'], ['Central star', 'WR 136']]),
  P('Egg Nebula', 'Egg Nebula', 'nebula', 315.58, 36.69, '~3,000 ly',
    'The prototype of a star caught between lives: no longer a red giant, not yet a planetary nebula, with searchlight beams escaping through gaps in its cocoon of dust.',
    [['Type', 'Protoplanetary nebula'], ['Beams', 'Searchlight pairs']]),
  P('Barnard 68', 'Barnard 68', 'nebula', 260.66, -23.83, '500 ly',
    'A small dark cloud so dense and cold it blots out every star behind it — a "hole in the sky" that will quietly collapse into a new star in a few hundred thousand years.',
    [['Type', 'Bok globule'], ['Fate', 'Will form a star']]),
  P('M97', 'Owl Nebula', 'nebula', 168.70, 55.02, '2,030 ly',
    'A round planetary nebula in the Big Dipper whose two dark hollows stare back like an owl\'s face — a dying star\'s wind seen slightly askew.',
    [['Type', 'Planetary nebula'], ['Age', '~8,000 yr']]),
  P('NGC 7009', 'Saturn Nebula', 'nebula', 316.04, -11.36, '~5,000 ly',
    'A planetary nebula with handles: twin jets punch through its bright shell and end in glowing knots, giving it the silhouette of the planet Saturn.',
    [['Type', 'Planetary nebula'], ['Jets', 'Twin ansae']]),
  P('IC 2118', 'Witch Head Nebula', 'nebula', 76.73, -7.22, '~900 ly',
    'A wisp of dust shaped uncannily like a cackling profile, glowing blue with the reflected light of brilliant Rigel next door.',
    [['Type', 'Reflection nebula'], ['Lit by', 'Rigel']]),
  P('NGC 7635', 'Bubble Nebula', 'nebula', 350.19, 61.20, '7,100 ly',
    'A near-perfect sphere seven light-years wide, inflated by the wind of a single massive star burning forty times brighter than the Sun off-centre inside it.',
    [['Bubble', '~7 ly across'], ['Blown by', 'One O star']]),
  P('IC 5070', 'Pelican Nebula', 'nebula', 312.75, 44.37, '1,800 ly',
    'The North America Nebula\'s neighbour across a dark dust channel, its pelican profile slowly being eroded and re-carved by the young stars igniting inside it.',
    [['Type', 'Emission nebula'], ['Neighbour', 'North America Nebula']]),
  P('IC 1396', "Elephant's Trunk", 'nebula', 324.78, 57.50, '2,400 ly',
    'A winding trunk of dense gas twenty light-years long, compressed by radiation from a nearby giant star and quietly forming new stars inside its tip.',
    [['Length', '~20 ly'], ['State', 'Forming stars']]),
  P('MyCn 18', 'Hourglass Nebula', 'nebula', 204.90, -67.38, '8,000 ly',
    'A dying star\'s wind caught in a perfect hourglass, with an eerie "eye" staring from the centre — one of Hubble\'s most famous portraits.',
    [['Type', 'Planetary nebula'], ['Shape', 'Hourglass + eye']]),
  P('Mz 3', 'Ant Nebula', 'nebula', 244.31, -51.99, '~4,500 ly',
    'Twin lobes blasting from a dying star at 1,000 km/s in the shape of an ant — winds so extreme they hint at a hidden companion star shaping the outflow.',
    [['Type', 'Bipolar planetary'], ['Outflow', '~1,000 km/s']]),
  P('NGC 7023', 'Iris Nebula', 'nebula', 315.40, 68.17, '1,300 ly',
    'A blue rose of dust unfolding around a young star — a reflection nebula whose grains glow with an unexplained red fluorescence at its heart.',
    [['Type', 'Reflection nebula'], ['Span', '~6 ly']]),
  P('NGC 1499', 'California Nebula', 'nebula', 60.83, 36.42, '1,000 ly',
    'A hundred-light-year ribbon of glowing hydrogen shaped like the state of California, energised by the scorching runaway star Xi Persei below it.',
    [['Length', '~100 ly'], ['Lit by', 'Xi Persei']]),
  P('Sh2-155', 'Cave Nebula', 'nebula', 344.20, 62.62, '2,400 ly',
    'A hollow of glowing gas opening into a wall of dark dust — a cave whose ceiling is being eaten away by the light of newborn stars above it.',
    [['Type', 'Emission + dark nebula'], ['State', 'Star-forming rim']]),

  // ---- Star-forming regions ----
  P('30 Doradus', 'Tarantula Nebula', 'starforming', 84.68, -69.10, '160,000 ly',
    'The most active starburst region in the Local Group, in the Large Magellanic Cloud, home to the most massive stars known.',
    [['Type', 'Starburst'], ['Hosts', 'R136 cluster']]),
  P('Rho Oph', 'Rho Ophiuchi Cloud', 'starforming', 246.79, -24.62, '460 ly',
    'The nearest stellar nursery, a colourful complex of dust and protostars, a JWST first-anniversary image.',
    [['Type', 'Molecular cloud'], ['Nearest nursery', 'yes']]),
  P('NGC 3603', 'NGC 3603', 'starforming', 168.80, -61.26, '20,000 ly',
    'A giant H II region packing some of the densest concentrations of massive stars in the galaxy.',
    [['Type', 'H II region'], ['Stars', 'Very massive']]),
  P('Westerlund 1', 'Westerlund 1', 'starforming', 251.77, -45.85, '~13,000 ly',
    'The most massive young star cluster in the galaxy, crowded with rare hypergiants and Wolf–Rayet stars — and hidden behind so much dust it went unnoticed until 1961.',
    [['Type', 'Super star cluster'], ['Mass', '~50,000 M☉']]),
  P('Sgr B2', 'Sagittarius B2', 'starforming', 266.83, -28.38, '25,000 ly',
    'A giant molecular cloud near the galactic centre laced with organic molecules — including ethyl formate, the compound that gives raspberries their flavour.',
    [['Type', 'Molecular cloud'], ['Contains', 'Ethyl formate'], ['Mass', '~3 million M☉']]),
  P('NGC 604', 'NGC 604', 'starforming', 23.64, 30.78, '2.7 Mly',
    'One of the largest stellar nurseries known, in the Triangulum Galaxy — nearly a hundred times the span of the Orion Nebula, lit by two hundred newborn giant stars.',
    [['Span', '~1,500 ly'], ['Galaxy', 'M33 (Triangulum)']]),
  P('NGC 2024', 'Flame Nebula', 'starforming', 85.43, -1.85, '1,350 ly',
    'A burning-bush of a nebula beside Alnitak in Orion\'s belt, split by a dark lane of dust hiding a cluster of infant stars at its heart.',
    [['Type', 'Emission nebula'], ['In', "Orion's belt"]]),
  P('Westerlund 2', 'Westerlund 2', 'starforming', 155.99, -57.76, '20,000 ly',
    'A young super-cluster carving glowing pillars out of its birth cloud — the sparkling centrepiece Hubble chose for its 25th-anniversary portrait.',
    [['Age', '~2 Myr'], ['Stars', '~3,000']]),
  P('Arches', 'Arches Cluster', 'starforming', 266.46, -28.82, '25,000 ly',
    'The densest star cluster known in the galaxy: thousands of stars packed within a single light-year, orbiting perilously close to the galactic centre.',
    [['Density', 'Highest known'], ['Near', 'Galactic centre']]),
  P('IC 1805', 'Heart Nebula', 'starforming', 38.20, 61.45, '7,500 ly',
    'A vast heart-shaped cloud of glowing hydrogen, its chambers hollowed out by the winds of the young cluster beating at its centre.',
    [['Span', '~200 ly'], ['Cluster', 'Melotte 15']]),
  P('IC 1848', 'Soul Nebula', 'starforming', 42.82, 60.42, '7,500 ly',
    'The Heart\'s companion cloud, pillared and cratered by newborn stars — together they span a stretch of the Perseus Arm four hundred light-years wide.',
    [['Partner', 'Heart Nebula'], ['Arm', 'Perseus']]),
  P('NGC 6357', 'War and Peace Nebula', 'starforming', 261.18, -34.20, '~5,900 ly',
    'A turbulent nursery housing Pismis 24, a cluster with some of the most massive stars known — one "star" there turned out to be several giants masquerading as one.',
    [['Cluster', 'Pismis 24'], ['Stars', '~100 M☉ class']]),

  // ---- Extreme stars ----
  P('Betelgeuse', 'Betelgeuse', 'star', 88.793, 7.407, '548 ly',
    'A red supergiant so large it would swallow Jupiter\'s orbit. It dimmed dramatically in 2019–20 and will explode as a supernova, astronomically soon.',
    [['Type', 'Red supergiant'], ['Radius', '~760 R☉'], ['Fate', 'Supernova']]),
  P('Eta Carinae', 'Eta Carinae', 'star', 161.265, -59.684, '7,500 ly',
    'A monstrous, unstable binary that staged a "Great Eruption" in the 1840s, briefly becoming the second-brightest star in the sky.',
    [['Type', 'Luminous blue variable'], ['Mass', '~100+ M☉']]),
  P('VY CMa', 'VY Canis Majoris', 'star', 110.74, -25.77, '3,840 ly',
    'One of the largest known stars: a red hypergiant roughly 1,400 times the Sun\'s radius, shedding huge amounts of mass.',
    [['Type', 'Red hypergiant'], ['Radius', '~1,420 R☉']]),
  P('R136a1', 'R136a1', 'star', 84.675, -69.10, '160,000 ly',
    'The most massive star known, blazing in the Tarantula Nebula at millions of times the Sun\'s luminosity.',
    [['Mass', '~196 M☉'], ['Most massive star', 'yes']]),
  P('Sirius B', 'Sirius B', 'star', 101.287, -16.716, '8.6 ly',
    'The nearest white dwarf: an Earth-sized stellar ember as massive as the Sun, orbiting brilliant Sirius A.',
    [['Type', 'White dwarf'], ['Density', 'Extreme']]),
  P('Algol', 'Algol (Demon Star)', 'star', 47.042, 40.956, '90 ly',
    'The prototype eclipsing binary: every 2.87 days a dim companion passes in front, visibly dimming the star.',
    [['Type', 'Eclipsing binary'], ['Period', '2.87 d']]),
  P('SS 433', 'SS 433', 'star', 287.957, 4.98, '18,000 ly',
    'A microquasar firing precessing jets at a quarter the speed of light, the first known "Galactic" relativistic-jet source.',
    [['Type', 'Microquasar'], ['Jets', '0.26c']]),
  P('Mira', 'Mira (The Wonderful)', 'star', 34.84, -2.98, '300 ly',
    'The first variable star ever recognised (1596), swelling and fading over 11 months — and trailing a 13-light-year tail of shed material like a comet.',
    [['Type', 'Pulsating red giant'], ['Tail', '13 ly long'], ['First variable known', '1596']]),
  P('Tabby', "Tabby's Star (KIC 8462852)", 'star', 301.56, 44.46, '1,470 ly',
    'The star whose bizarre, irregular dimmings briefly made "alien megastructure" a serious hypothesis. The culprit appears to be fine dust — but the light curve remains unique.',
    [['Dips', 'Up to 22%'], ['Cause', 'Dust (probably)']]),
  P('Przybylski', "Przybylski's Star", 'star', 174.40, -46.71, '~370 ly',
    'The strangest chemistry in the sky: an atmosphere loaded with rare-earth elements and, apparently, short-lived radioactive ones that shouldn\'t persist — no accepted explanation yet.',
    [['Type', 'Peculiar Ap star'], ['Mystery', 'Unstable elements']]),
  P('WR 104', 'WR 104 (Pinwheel Star)', 'star', 270.52, -23.63, '8,400 ly',
    'A dying Wolf–Rayet star wrapped in a perfect spiral of dust wound by its orbit with a companion. It was once feared its future gamma-ray burst might point at Earth; it almost certainly doesn\'t.',
    [['Type', 'Wolf–Rayet binary'], ['Dust spiral', '1 turn / 220 d']]),
  P('Van Maanen', "Van Maanen's Star", 'star', 12.29, 5.39, '14 ly',
    'The nearest solitary white dwarf, and the first star ever caught "polluted" by the debris of its own planetary system — evidence of dead worlds around a dead star.',
    [['Type', 'White dwarf'], ['Atmosphere', 'Planet debris']]),
  P('Luhman 16', 'Luhman 16', 'star', 162.33, -53.32, '6.5 ly',
    'The third-closest system to the Sun, discovered only in 2013: a pair of brown dwarfs — failed stars — one of which has mapped cloud weather.',
    [['Type', 'Brown dwarf pair'], ['Distance rank', '3rd closest system']]),
  P('WISE 0855', 'WISE 0855−0714', 'star', 133.79, -7.25, '7.4 ly',
    'The coldest known object outside a solar system that formed like a star: a brown dwarf below the freezing point of water, likely with clouds of ice.',
    [['Temperature', '−20 °C'], ['Type', 'Y-class brown dwarf']]),
  P('T Tauri', 'T Tauri', 'star', 65.50, 19.54, '470 ly',
    'The prototype newborn star: still contracting toward the main sequence, wrapped in gas and dust. Every infant Sun-like star is called a "T Tauri star" after it.',
    [['Type', 'Pre-main-sequence'], ['Age', '<1 Myr']]),
  P('Scholz', "Scholz's Star", 'star', 110.01, -8.78, '22 ly',
    'A dim red dwarf that grazed the Sun\'s Oort cloud 70,000 years ago, within one light-year — the closest known stellar flyby, likely seen by early humans only as occasional flares.',
    [['Flyby', '70,000 yr ago'], ['Closest approach', '~0.85 ly']]),
  P('Zeta Oph', 'Zeta Ophiuchi', 'star', 249.29, -10.57, '366 ly',
    'A runaway star flung loose when its companion exploded, now ploughing through interstellar gas behind a glowing bow shock at 30 km/s.',
    [['Type', 'Runaway O star'], ['Speed', '~30 km/s']]),
  P('Delta Cephei', 'Delta Cephei', 'star', 337.29, 58.42, '890 ly',
    'The prototype Cepheid variable: its steady pulse of brightening and fading calibrates the cosmic distance ladder. Stars like this one taught us how big the universe is.',
    [['Type', 'Cepheid prototype'], ['Period', '5.37 d'], ['Discovered variable', '1784']]),
  P('RS Oph', 'RS Ophiuchi', 'star', 267.55, -6.71, '~5,000 ly',
    'A white dwarf that erupts as a naked-eye nova roughly every fifteen years as gas from its red-giant companion detonates on its surface. One day the eruptions will end in a supernova.',
    [['Type', 'Recurrent nova'], ['Last eruption', '2021'], ['Fate', 'Type Ia supernova']]),
  P('HD 140283', 'Methuselah Star', 'star', 235.76, -10.93, '190 ly',
    'One of the oldest stars known — early measurements made it appear older than the universe itself. Refined ages resolved the paradox, barely: it formed within the first billion years.',
    [['Age', '~13.5 Gyr'], ['Metals', 'Almost none']]),
  P('V838 Mon', 'V838 Monocerotis', 'star', 106.02, -3.85, '20,000 ly',
    'In 2002 this star erupted and briefly outshone a million Suns; Hubble then filmed a "light echo" — the flash sweeping outward through shells of dust, illuminating them year by year like rings of a bell.',
    [['Event', 'Luminous red nova'], ['Light echo', 'Filmed by Hubble']]),
  P('40 Eri B', '40 Eridani B', 'star', 63.84, -7.65, '16.3 ly',
    'The first white dwarf ever identified, and the easiest to see in a backyard telescope — a dead star\'s core shining faintly beside its orange companion.',
    [['Type', 'White dwarf'], ['First identified', '1914'], ['Amateur visible', 'yes']]),
  P('R CrB', 'R Coronae Borealis', 'star', 237.14, 28.16, '~5,000 ly',
    'A star that vanishes: every few years it forges clouds of carbon soot that block its own light, fading a thousandfold before the soot blows clear. The prototype "inverse nova".',
    [['Type', 'R CrB variable'], ['Dims by', '~1,000×'], ['Cause', 'Carbon soot']]),
  P('Pistol Star', 'Pistol Star', 'star', 266.56, -28.83, '25,000 ly',
    'One of the most luminous stars known, hiding near the galactic centre behind walls of dust. It has already blown off a nebula holding ten Suns\' worth of its own shed mass.',
    [['Luminosity', '~1.6 million L☉'], ['Shed mass', '~10 M☉']]),
  P('Polaris', 'Polaris', 'star', 37.95, 89.26, '433 ly',
    'The North Star is no ordinary landmark: it is the nearest Cepheid variable, gently pulsing every four days — and Earth\'s wobbling axis will hand its title to other stars over millennia.',
    [['Type', 'Cepheid'], ['Period', '3.97 d'], ['Pole star until', '~3000 AD']]),
  P('Eps Aur', 'Epsilon Aurigae', 'star', 75.49, 43.82, '~2,000 ly',
    'Every 27 years this bright star dims for two full years, eclipsed by a vast dark disk of dust around an unseen companion — a mystery observed since 1821 and still not fully solved.',
    [['Eclipse', 'Every 27.1 yr'], ['Duration', '~2 yr'], ['Eclipser', 'Dark disk']]),
  P('P Cygni', 'P Cygni', 'star', 304.45, 38.03, '5,600 ly',
    'In 1600 this star simply appeared where none had been, then faded — a luminous blue variable in permanent slow eruption. Its spectral signature of expanding gas now bears its name.',
    [['Type', 'Luminous blue variable'], ['Appeared', '1600 AD']]),
  P('Rho Cas', 'Rho Cassiopeiae', 'star', 358.60, 57.50, '8,200 ly',
    'A yellow hypergiant — one of the rarest kinds of star — that coughs off half an Earth-mass of gas per day and stages massive outbursts every few decades. A supernova in waiting.',
    [['Type', 'Yellow hypergiant'], ['Outbursts', '1946 · 2000 · 2013']]),
  P('IK Peg', 'IK Pegasi', 'star', 321.61, 19.38, '154 ly',
    'The nearest known candidate for a future Type Ia supernova: a white dwarf close to the critical mass, orbiting an ordinary star barely 150 light-years from home.',
    [['Type', 'SN Ia progenitor'], ['Nearest candidate', 'yes']]),
  P('HE 0107-5240', 'HE 0107−5240', 'star', 17.37, -52.41, '36,000 ly',
    'A halo star made of almost pure hydrogen and helium — nearly untouched Big Bang material. It carries less iron than any star known when found, a fossil of the first stellar generations.',
    [['Iron', '1/200,000th of Sun'], ['Age', '~13 Gyr']]),
  P('UV Ceti', 'UV Ceti', 'star', 24.75, -17.95, '8.7 ly',
    'The prototype flare star: a tiny red dwarf next door that can brighten a hundredfold in minutes when its surface snaps with magnetic explosions.',
    [['Type', 'Flare star prototype'], ['Flares', '~100× in minutes']]),
  P('Mu Cephei', 'Mu Cephei (Garnet Star)', 'star', 325.88, 58.78, '~2,800 ly',
    'Herschel\'s "garnet star": one of the largest and reddest stars visible to the naked eye, a supergiant that would reach past Jupiter if placed at the Sun.',
    [['Type', 'Red supergiant'], ['Radius', '~1,000 R☉']]),
  P('La Superba', 'La Superba (Y CVn)', 'star', 191.28, 45.44, '~800 ly',
    'Among the reddest stars in the sky: a carbon star whose sooty atmosphere filters its light to a deep ember-red that startled 19th-century observers.',
    [['Type', 'Carbon star'], ['Colour', 'Deepest red']]),
  P('BPM 37093', 'Lucy — the Diamond Star', 'star', 189.71, -49.80, '50 ly',
    'A white dwarf whose crystallised carbon core is, in effect, a diamond of ten billion trillion trillion carats — a preview of what the Sun\'s remnant will become.',
    [['Type', 'Crystallised white dwarf'], ['Core', 'Diamond-like carbon']]),
  P('CK Vul', 'CK Vulpeculae (Nova 1670)', 'star', 296.91, 27.31, '~10,000 ly',
    'The "nova" of 1670 that refuses to be explained: modern telescopes find cool molecular debris and even radioactive dust — perhaps the wreckage of two stars that merged.',
    [['Event', '1670 AD'], ['Nature', 'Likely stellar merger']]),
  P('Zeta Puppis', 'Zeta Puppis (Naos)', 'star', 120.90, -40.00, '1,080 ly',
    'The hottest star easily seen with the naked eye — a 40,000-degree runaway giant whose fierce ultraviolet light ionises the gas for light-years around it.',
    [['Surface', '~40,000 K'], ['Type', 'Runaway O supergiant']]),
  P('Cyg OB2-12', 'Cygnus OB2 #12', 'star', 308.17, 41.24, '~5,500 ly',
    'One of the most luminous stars known in the galaxy, hidden in plain sight: dust dims its light ten-thousandfold, or it would shine among the brightest stars in our sky.',
    [['Luminosity', '~2 million L☉'], ['Dimmed by dust', '~10 mag']]),
  P('EBLM J0555-57', 'Smallest Star', 'star', 88.88, -57.29, '630 ly',
    'The smallest known true star: barely larger than Saturn, with just enough mass to sustain hydrogen fusion. Any smaller and it would merely be a warm brown dwarf.',
    [['Size', '~Saturn'], ['Mass', '~85 M♃ — the minimum']]),
  P('Earendel', 'Earendel', 'star', 24.35, -8.46, '12.9 Gly',
    'The most distant single star ever seen, magnified thousands of times by a lucky alignment of galaxy-cluster gravity — starlight from the universe\'s first billion years.',
    [['Most distant star', 'yes'], ['Seen via', 'Gravitational lens']]),

  // ---- Exoplanet systems ----
  P('TRAPPIST-1', 'TRAPPIST-1', 'exoplanet', 346.62, -5.04, '40 ly',
    'A cool red dwarf with seven Earth-sized planets, three in the habitable zone, the richest nearby system for studying rocky worlds.',
    [['Planets', '7'], ['Habitable zone', '3 planets']]),
  P('51 Pegasi', '51 Pegasi', 'exoplanet', 344.366, 20.769, '50 ly',
    'Host of 51 Peg b (1995), the first exoplanet found around a Sun-like star, a discovery that won the 2019 Nobel Prize.',
    [['First exoplanet (Sun-like)', '1995'], ['Planet', 'Hot Jupiter']]),
  P('Kepler-90', 'Kepler-90', 'exoplanet', 285.43, 49.31, '2,840 ly',
    'A Sun-like star with eight known planets, tying our own Solar System for the most planets in one system.',
    [['Planets', '8'], ['Ties', 'Solar System']]),
  P('HD 209458', 'HD 209458 (Osiris)', 'exoplanet', 330.795, 18.884, '159 ly',
    'The first exoplanet seen transiting its star and the first with a detected atmosphere, evaporating into a comet-like tail.',
    [['First transit', '1999'], ['Atmosphere', 'Detected']]),
  P('Proxima Centauri', 'Proxima Centauri', 'exoplanet', 217.429, -62.679, '4.24 ly',
    'The closest star to the Sun, hosting Proxima b, a roughly Earth-mass planet in its habitable zone, the nearest such world.',
    [['Planets', '2+'], ['Nearest exoplanet', 'Proxima b']]),
  P('Kepler-186', 'Kepler-186', 'exoplanet', 298.65, 43.95, '580 ly',
    'Home of Kepler-186f, the first Earth-sized planet found in another star\'s habitable zone (2014) — a world that could, in principle, hold liquid water.',
    [['Kepler-186f', 'First Earth-size in HZ'], ['Planets', '5']]),
  P('55 Cancri', '55 Cancri', 'exoplanet', 133.15, 28.33, '41 ly',
    'A naked-eye star with five planets, including 55 Cancri e: a lava world twice Earth\'s size, so close to its sun that its year lasts 18 hours.',
    [['Planets', '5'], ['55 Cnc e', 'Lava world, 18-hr year']]),
  P('HR 8799', 'HR 8799', 'exoplanet', 346.87, 21.13, '133 ly',
    'The first planetary system ever photographed directly (2008): four giant planets visibly orbiting their star across a decade of images.',
    [['Planets imaged', '4'], ['First direct image', '2008']]),
  P('Beta Pictoris', 'Beta Pictoris', 'exoplanet', 86.82, -51.07, '63 ly',
    'A young star ringed by a spectacular debris disk with a giant planet sweeping through it — planet formation caught in the act.',
    [['Planets', '2'], ['Debris disk', 'Edge-on']]),
  P('Kepler-16', 'Kepler-16 (Tatooine)', 'exoplanet', 289.08, 51.76, '245 ly',
    'The first confirmed planet orbiting two suns (2011). From Kepler-16b\'s cloud tops, every day ends with a double sunset.',
    [['Planet', 'Circumbinary'], ['Suns', '2']]),
  P('HD 189733', 'HD 189733', 'exoplanet', 300.18, 22.71, '64.5 ly',
    'Host of the deep-blue planet HD 189733 b — beautiful from afar, but the colour comes from silicate clouds: on a world of 2 km/s winds, it likely rains molten glass sideways.',
    [['Colour', 'Cobalt blue'], ['Weather', 'Molten glass rain']]),
  P('GJ 1214', 'GJ 1214', 'exoplanet', 258.83, 4.96, '48 ly',
    'Host of the archetypal "water world" candidate: a sub-Neptune whose density suggests a planet largely made of steam and ocean.',
    [['GJ 1214 b', 'Possible water world'], ['Type', 'Sub-Neptune']]),
  P('Kepler-452', 'Kepler-452', 'exoplanet', 296.00, 44.28, '1,800 ly',
    'Home of Kepler-452b, "Earth\'s older cousin": a slightly larger world in the habitable zone of a Sun-like star half a billion years older than ours.',
    [['Kepler-452b', 'Earth\'s cousin'], ['Year', '385 days']]),
  P('TOI-700', 'TOI-700', 'exoplanet', 97.10, -65.58, '101 ly',
    'TESS\'s first Earth-sized habitable-zone discovery: TOI-700 d, a quiet red dwarf\'s temperate world — later joined by a second one in the same zone.',
    [['HZ planets', '2'], ['Found by', 'TESS (2020)']]),
  P('K2-18', 'K2-18', 'exoplanet', 172.56, 7.59, '124 ly',
    'Host of K2-18 b, a possible "hycean" world — a hydrogen-skied planet that may hide a global ocean, where JWST has hunted for gases that on Earth only life produces.',
    [['K2-18 b', 'Hycean candidate'], ['JWST', 'Atmosphere probed']]),
  P('GJ 876', 'Gliese 876', 'exoplanet', 343.32, -14.26, '15 ly',
    'One of the nearest planetary systems: four planets around a red dwarf, three locked in a gravitational resonance chain that repeats like clockwork every 124 days.',
    [['Planets', '4'], ['Resonance', '1:2:4 chain']]),
  P('Epsilon Eridani', 'Epsilon Eridani (Ran)', 'exoplanet', 53.23, -9.46, '10.5 ly',
    'The nearest planetary system around a young Sun-like star: a Jupiter analogue and two asteroid belts — a picture of what our own system may have looked like at one billion years old.',
    [['Planet', 'Jupiter analogue'], ['Debris belts', '2'], ['Age', '~800 Myr']]),
  P('PSR B1620-26', 'Methuselah Planet', 'exoplanet', 245.91, -26.53, '12,400 ly',
    'The oldest planet known: a gas giant nearly 13 billion years old, orbiting a pulsar and a white dwarf in the globular cluster M4 — a world older than the galaxy\'s disk.',
    [['Age', '~12.7 Gyr'], ['Suns', 'Pulsar + white dwarf']]),
  P('WASP-76', 'WASP-76', 'exoplanet', 26.63, 2.70, '~640 ly',
    'Home of an ultra-hot giant where daytime reaches 2,400 °C — hot enough to vaporise iron, which then condenses and rains as molten metal along the evening edge of the planet.',
    [['WASP-76 b', 'Iron rain'], ['Day side', '~2,400 °C']]),
  P('Kepler-444', 'Kepler-444', 'exoplanet', 289.75, 41.63, '119 ly',
    'Five rocky planets orbiting a star 11 billion years old — proof that the universe was building small stony worlds when it was barely a fifth of its current age.',
    [['Planets', '5 (all sub-Earth)'], ['Age', '~11.2 Gyr']]),
  P('PDS 70', 'PDS 70', 'exoplanet', 212.04, -41.40, '370 ly',
    'The only place where planets have been photographed while still forming: two newborn giants clearing a gap in their star\'s disk, one still wearing its own moon-forming disk.',
    [['Planets imaged forming', '2'], ['Moon-forming disk', 'Seen']]),
  P('Tau Ceti', 'Tau Ceti', 'exoplanet', 26.02, -15.94, '11.9 ly',
    'The nearest single Sun-like star, wrapped in a thick debris disk with four candidate planets — and a fixture of every SETI target list since 1960.',
    [['Candidate planets', '4'], ['SETI target since', '1960']]),
  P('Gliese 581', 'Gliese 581', 'exoplanet', 229.86, -7.72, '20.4 ly',
    'The system that launched the habitable-zone gold rush: its super-Earths were the first widely argued to be potentially livable, including one famous planet that turned out not to exist.',
    [['Planets', '3 confirmed'], ['Gliese 581g', 'Retracted']]),
  P('GJ 667C', 'Gliese 667C', 'exoplanet', 259.74, -34.99, '23.6 ly',
    'A red dwarf in a triple-star system with a super-Earth in its habitable zone — from its surface, two extra suns hang in the sky like brilliant lamps.',
    [['HZ planet', 'GJ 667C c'], ['Suns in its sky', '3']]),
  P('Kepler-11', 'Kepler-11', 'exoplanet', 297.12, 41.91, '2,150 ly',
    'Six planets packed so tightly that five orbit closer than Mercury does to the Sun — the discovery that showed planetary systems can be built nothing like ours.',
    [['Planets', '6'], ['Announced', '2011']]),
  P('CoRoT-7', 'CoRoT-7', 'exoplanet', 100.96, -1.06, '~490 ly',
    'Home of CoRoT-7b, the first rocky exoplanet ever confirmed (2009): a lava-surfaced world circling its star in twenty hours.',
    [['CoRoT-7b', 'First rocky exoplanet'], ['Year', '20.5 hr']]),
  P('WASP-96', 'WASP-96', 'exoplanet', 1.05, -47.36, '1,150 ly',
    'The planet JWST chose for its very first spectrum release: a puffy hot gas giant whose atmosphere showed the unmistakable signature of water and haze.',
    [['JWST first spectrum', '2022'], ['Found', 'Water vapour']]),
  P('51 Eridani', '51 Eridani', 'exoplanet', 69.40, -2.47, '96 ly',
    'Home of 51 Eri b, the most Jupiter-like young planet ever imaged directly — methane-rich and only twenty million years old, a baby picture of our own giant.',
    [['51 Eri b', 'Young Jupiter, imaged'], ['Age', '~20 Myr']]),
  P('Kepler-1625', 'Kepler-1625', 'exoplanet', 295.43, 39.39, '8,000 ly',
    'The system with the first serious exomoon candidate: hints of a Neptune-sized moon orbiting a giant planet — still contested, still tantalising.',
    [['Exomoon candidate', 'First found'], ['Status', 'Debated']]),
  P('TrES-2', 'TrES-2 (Darkest Planet)', 'exoplanet', 286.81, 49.32, '750 ly',
    'Home of the darkest planet known: a gas giant blacker than coal, reflecting less than one percent of the light that strikes it. Why it is so dark remains unclear.',
    [['Albedo', '<1%'], ['Darker than', 'Coal']]),
  P('KELT-9', 'KELT-9 (Hottest Planet)', 'exoplanet', 307.86, 39.94, '670 ly',
    'The hottest planet known: its dayside reaches 4,300 °C — hotter than many stars — so hot that iron and titanium float in its sky as vaporised metal atoms.',
    [['Dayside', '~4,300 °C'], ['Sky contains', 'Iron vapour']]),
  P('HD 80606', 'HD 80606', 'exoplanet', 140.66, 50.60, '217 ly',
    'A giant planet on the most eccentric orbit known — a comet-like path that swings from Earth-like distance to a searing close pass, its weather exploding on each approach.',
    [['Eccentricity', '0.93'], ['Orbit', 'Comet-like']]),
  P('GJ 504', 'Gliese 504', 'exoplanet', 199.20, 9.42, '57 ly',
    'Home of a directly-imaged giant that glows a deep magenta — a just-cooling young world whose colour comes straight from its own residual heat.',
    [['GJ 504 b', 'Magenta, imaged'], ['State', 'Still cooling']]),
  P('Fomalhaut b', 'Fomalhaut b (Dagon)', 'exoplanet', 344.41, -29.62, '25 ly',
    'The exoplanet that vanished: hailed as the first directly imaged planet in 2008, it slowly dissolved before Hubble\'s eyes — almost certainly a drifting cloud from a giant collision.',
    [['Status', 'Was never a planet'], ['Actually', 'Collision debris']]),
  P('Barnard', "Barnard's Star", 'exoplanet', 269.45, 4.69, '6.0 ly',
    'The nearest single star, famous for racing across our sky faster than any other — and since 2024, confirmed home of a rocky planet smaller than Earth.',
    [['Barnard b', 'Confirmed 2024'], ['Proper motion', 'Fastest known']]),

  // ---- Gravitational-wave events (approximate sky positions) ----
  P('GW150914', 'GW150914', 'gw', 112.0, -70.0, '1.3 Gly',
    'The first direct detection of gravitational waves (2015): the merger of two black holes ~1.3 billion years ago, confirming Einstein and launching a new astronomy.',
    [['Source', '36+29 M☉ black holes'], ['First detection', '2015']]),
  P('GW170817', 'GW170817', 'gw', 197.45, -23.38, '130 Mly',
    'The first neutron-star merger seen in both gravitational waves and light (in galaxy NGC 4993): a kilonova that forged heavy elements like gold.',
    [['Source', 'Neutron-star merger'], ['Made', 'Heavy elements']]),
  P('GW190521', 'GW190521', 'gw', 192.0, 35.0, '~17 Gly',
    'The merger that produced an intermediate-mass black hole of ~142 M☉, bridging stellar and supermassive scales.',
    [['Result', '~142 M☉ black hole'], ['Class', 'Intermediate-mass']]),
  P('GW190814', 'GW190814', 'gw', 12.0, -25.0, '790 Mly',
    'A black hole swallowing a 2.6-solar-mass mystery object — too heavy to be any known neutron star, too light to be any known black hole. It sits exactly in the "mass gap".',
    [['Mystery object', '2.6 M☉'], ['Class', 'Mass-gap merger']]),

  // ---- Radio transients (fast radio bursts & famous signals) ----
  P('FRB 010724', 'Lorimer Burst', 'radio', 19.53, -75.2, '~3 Gly',
    'The first fast radio burst ever found, spotted in 2007 in archival pulsar data: a 5-millisecond radio flash from far beyond the galaxy that opened an entirely new mystery.',
    [['Duration', '~5 ms'], ['Found', '2007 (archival)'], ['Class', 'First FRB']]),
  P('FRB 121102', 'First Repeating FRB', 'radio', 82.99, 33.15, '~3 Gly',
    'The first fast radio burst seen to repeat, which let astronomers pin it to a dwarf galaxy three billion light-years away — proving FRBs are real cosmic sources, not glitches.',
    [['Repeats', 'Yes'], ['Host', 'Dwarf galaxy'], ['Localized', '2017']]),
  P('FRB 20180916B', 'FRB 20180916B', 'radio', 29.50, 65.72, '460 Mly',
    'A repeating fast radio burst with a strict 16.35-day activity cycle — the first periodic FRB, hinting at an orbiting or precessing source.',
    [['Period', '16.35 days'], ['Class', 'Periodic repeater']]),
  P('Wow! Signal', 'Wow! Signal', 'radio', 291.38, -26.95, 'Unknown',
    'A 72-second narrowband radio burst caught by Ohio State\'s "Big Ear" telescope in 1977, so striking the astronomer wrote "Wow!" on the printout. Never detected again; its origin is still unexplained. (Position is one of two candidate beams.)',
    [['Detected', 'Aug 15, 1977'], ['Duration', '72 s'], ['Repeated', 'Never']]),

  // ---- Gamma-ray bursts ----
  P('GRB 221009A', 'The BOAT — Brightest Burst Ever', 'grb', 288.26, 19.77, '2.4 Gly',
    'The Brightest Of All Time: a 2022 gamma-ray burst so intense it saturated detectors and measurably disturbed Earth\'s ionosphere from 2.4 billion light-years away — likely a once-in-10,000-years event.',
    [['Nickname', 'The BOAT'], ['Ionosphere', 'Disturbed'], ['Rarity', '~1 in 10,000 yr']]),
  P('GRB 080319B', 'GRB 080319B', 'grb', 217.92, 36.30, '7.5 Gly',
    'For about 30 seconds in 2008 this dying star was visible to the naked eye from 7.5 billion light-years away — the most distant object human eyes have ever been able to see.',
    [['Naked-eye', '~30 s'], ['Peak mag', '5.3'], ['Record', 'Farthest visible object']]),
  P('GRB 090423', 'GRB 090423', 'grb', 148.89, 18.15, '~13 Gly',
    'The death of a star when the universe was only 630 million years old — for a time the most distant object ever observed, a beacon from the era of the first stars.',
    [['Redshift', 'z = 8.2'], ['Universe age', '630 Myr']]),
];
